### ISSUE TITLE
Vamos a eliminar esos errores de consola!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m3-evaluacion-intermedia-cristinatato#1]
Buen trabajo @cristinatato  !

Algunas pistas para acabarlo:

- [x] Como sugerencia general, comprueba continuamente tu aplicación en Chrome y el terminal dónde arrancas la app con `npm start`. Si algo falla, hay que arreglarlo antes de continuar.
- [x] Si utilizas SASS, recuerda instalarlo y grabarlo en el package.json con `--save`

- [x] Añade estilos (un archivo sass o css por componente)
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by cristinatato** [comment]
Hi @oneeyedman ! I made some changes to improve my exercise and fix the issues! 
Thank you!

**Comment by oneeyedman** [comment]
Adelante!
